### PR TITLE
Restrict `any` and all` argument type bounds

### LINKED ISSUE #132: Loading `Static.jl` with the latest julia nightly build makes `all(::Tuple{})` ambiguous
**This is not an issue when using the latest official release from Julia**, but it is an issue when using the julia nightly build, so it may become an issue in the future.

When using the julia nightly build with `Static.jl` loaded, `all(())` throws a `MethodError`.

In commit [75cb2f6](https://github.com/JuliaLang/julia/commit/75cb2f60af7e1d0a2dd5472ff2390600aa083db2) to julia, this method: `all(x::Tuple{}) = true` was removed. 

It looks like [these](https://github.com/SciML/Static.jl/blob/2e254a37b294f63407d2b486b6d09d2806e7a216/src/Static.jl#L520-L526) lines in `Static.jl` need that method to resolve the ambiguity when the argument is an empty tuple. 

This also applies to `any(::Tuple{})`

**Expected behavior**

When `Static.jl` is loaded, `all(())` should evaluate to true.

**Minimal Reproducible Example 👇**

```julia
julia> all(())
true
julia> import Static

julia> all(())
ERROR: MethodError: all(::Tuple{}) is ambiguous.

Candidates:
  all(::Tuple{Vararg{Static.True}})
    @ Static ~/.julia/packages/Static/1Mvph/src/Static.jl:520
  all(::Tuple{Vararg{Static.False}})
    @ Static ~/.julia/packages/Static/1Mvph/src/Static.jl:522

Possible fix, define
  all(::Tuple{})

Stacktrace:
 [1] top-level scope
   @ REPL[3]:1
 [2] top-level scope
   @ REPL:1
```

**Error & Stacktrace ⚠️**

```julia
ERROR: MethodError: all(::Tuple{}) is ambiguous.

Candidates:
  all(::Tuple{Vararg{Static.True}})
    @ Static ~/.julia/packages/Static/1Mvph/src/Static.jl:520
  all(::Tuple{Vararg{Static.False}})
    @ Static ~/.julia/packages/Static/1Mvph/src/Static.jl:522

Possible fix, define
  all(::Tuple{})

Stacktrace:
 [1] top-level scope
   @ REPL[3]:1
 [2] top-level scope
   @ REPL:1
```

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
Status `/private/var/folders/tv/2nhhthmn2m91qsmlfz4yvynh0000gn/T/jl_PlU2fx/Project.toml`
  [aedffcd0] Static v1.1.1
```

  - Output of `using Pkg; Pkg.status(; mode = PKGMODE_MANIFEST)`

```julia
Status `/private/var/folders/tv/2nhhthmn2m91qsmlfz4yvynh0000gn/T/jl_PlU2fx/Manifest.toml`
  [f70d9fcc] CommonWorldInvalidations v1.0.0
  [615f187c] IfElse v0.1.1
  [aea7be01] PrecompileTools v1.2.1
  [21216c6a] Preferences v1.4.3
  [aedffcd0] Static v1.1.1
  [ade2ca70] Dates v1.11.0
  [de0858da] Printf v1.11.0
  [fa267f1f] TOML v1.0.3
  [4ec0a83e] Unicode v1.11.0
```

  - Output of `versioninfo()`

```julia
Julia Version 1.13.0-DEV.172
Commit 59320c62993 (2025-03-06 12:11 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 8 × Apple M3
  WORD_SIZE: 64
  LLVM: libLLVM-19.1.7 (ORCJIT, apple-m3)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 4 virtual cores)
```

**Additional context**

### PR DESCRIPTION
**Pull request by imreddyTeja**
This PR closes #132. 

Behavior does not change with the current Julia release, and the ambiguity is resolved for the nightly release.

Changes the argument types for the `any` and `all` methods on tuples to not rely on julia base definining
`all(::Tuple{}) = true` and `any(::Tuple{}) = false`.

## Checklist

- [x] Appropriate tests were added (code already covered by tests)
- [x] Any code changes were done in a way that does not break public API
- [x] All documentation related to code changes were updated
- [x] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [x] Any new documentation only uses public API
  
## Additional context

This is not an issue with the current Julia release, but it likely will be in the future.

### CODE REVIEW

File: src/Static.jl [hunk 1]
```diff
@@ -519,9 +519,9 @@ Base.:(!)(::False) = True()
 
 Base.all(::Tuple{Vararg{True}}) = true
 Base.all(::Tuple{Vararg{Union{True, False}}}) = false
-Base.all(::Tuple{Vararg{False}}) = false
+Base.all(::Tuple{False, Vararg{False}}) = false
```
Comment (devmotion) [inline src/Static.jl:522]: This will still add definitions for `Base.all(::Tuple{})` etc. since `Vararg`s maybe empty. To avoid this, arguments should be restricted to tuples of length >= 1:
```suggestion
Base.all(::Tuple{True, Vararg{True}}) = true
Base.all(::Tuple{Union{True,False}, Vararg{Union{True, False}}}) = false
```

File: src/Static.jl [hunk 2]
```diff
@@ -519,9 +519,9 @@ Base.:(!)(::False) = True()
...
 
-Base.any(::Tuple{Vararg{True}}) = true
+Base.any(::Tuple{True, Vararg{True}}) = true
 Base.any(::Tuple{Vararg{Union{True, False}}}) = true
 Base.any(::Tuple{Vararg{False}}) = false
```
Comment (devmotion) [inline src/Static.jl:526]: Similarly,
```suggestion
Base.any(::Tuple{False, Vararg{False}}) = false
Base.any(::Tuple{Union{True, False}, Vararg{Union{True, False}}}) = true
```

**Review by oscardssmith — APPROVED** [review]

File: src/Static.jl [hunk 3]
```diff
@@ -517,13 +517,11 @@ Base.xor(x::Union{Integer, Missing}, ::StaticInteger{Y}) where {Y} = xor(x, Y)
 Base.:(!)(::True) = False()
 Base.:(!)(::False) = True()
 
-Base.all(::Tuple{Vararg{True}}) = true
-Base.all(::Tuple{Vararg{Union{True, False}}}) = false
-Base.all(::Tuple{Vararg{False}}) = false
+Base.all(::Tuple{True, Vararg{True}}) = true
+Base.all(::Tuple{Union{True,False}, Vararg{Union{True, False}}}) = false
```
Comment (devmotion) [inline src/Static.jl:521]: AFAICT this will fix the formatting issue:
```suggestion
Base.all(::Tuple{Union{True, False}, Vararg{Union{True, False}}}) = false
```
